### ISSUE TITLE
About the completeness of this project

### ISSUE THREAD

**Issue by Ouyang-maxzx** [BehafaridMjf/Traffic-Assignment#2]
Hello, I am currently researching about coupling traffic network and distribution network, your code is very helpful for my programming, I would like to ask if this code is complete, and you want to implement

**Comment by BehafaridMjf** [comment]
Hello! I'm very happy you found my code useful!! The code is complete and you can definitely use that.

**Comment by BehafaridMjf** [comment]
> Hello, I am currently researching about coupling traffic network and distribution network, your code is very helpful for my programming, I would like to ask if this code is complete, and you want to implement

Hello! I'm very happy you found my code useful!! The code is complete and you can definitely use that.

**Comment by Ouyang-maxzx** [comment]
Hello!,My major is electrical engineering, but I'm currently researching the intersection of transportation and electricity. I tried your code and it works, but I don't know how to change your code to what I need. Sad, maybe you can teach me about traffic flow assignment.
